### ISSUE TITLE
Modified/dirty tabs not orange

### ISSUE THREAD

**Issue by skoch** [nilium/st2-nil-theme#1]
As you can see from the first screenshot, I'm working on Carousel.js and have switched over to master.less. In the sidebar, I can see that Carousel.js has been modified and not saved.
http://cl.ly/2p2n2s2b2g0m1P0L1M3Y

More of an issue without the sidebar:
http://cl.ly/0q123g3U2W0E2X0L1c3B

Or in fullscreen mode (as it doesn't show active files):
http://cl.ly/3E0z252N2w0H2O0l1e3p

**Comment by nilium** [comment]
Do you have `highlight_modified_tabs` enabled in your settings?

**Comment by skoch** [comment]
I did not. Didn't see it in the default either thus didn't know it was needed ... but all good now. Thanks!

**Comment by jeromegn** [comment]
Ah, that does fix it.
