### ISSUE TITLE
Tubnil color schemes don’t support markup scopes

### ISSUE THREAD

**Issue by sentience** [nilium/st2-nil-theme#10]
Syntax highlighting of markup scopes such as `markup.italic`, `markup.bold`, `markup.underline`, `markup.heading`, and `markup.list` (among others) are essential when editing Markdown and other text markup syntaxes. Tubnil and Tubnil Bright do not highlight these scopes. 

I’m happy to contribute a pull request, but if you’d prefer to select the colors I’m happy to stand back. Love the colors you’ve selected so far.

**Comment by nilium** [comment]
My personal view is that they're unnecessary for text markup languages unless you're somehow hiding the markup and using a font that supports all of the necessary formatting options. Making text stand out too much in Markdown, for example, would be rather bad -- it'd distract from the actual writing. So I have no plans to fix this nor to accept any pull requests to fix it unless it's done in such a way that I don't notice it when editing Markdown.

**Comment by sentience** [comment]
Cool, thanks for the quick and clear reply.

And hooray for GitHub forks! :)

**Comment by sentience** [comment]
In case anyone is looking for markup syntax highlighting in the future, I’ve added it to my fork of this repo: 2431d594496c364f3a60eaa9b6fb81cef947e13f
