### ISSUE TITLE
in win8 ,drag directory split column to right,will cause a sublime crash

### ISSUE THREAD

**Issue by yangweijie** [nilium/st2-nil-theme#11]
Maybe it's the vc++ liabiray's problem
Here's a screenphoto 
![error pic](http://ww4.sinaimg.cn/large/50075709gw1dx0f4ssn19j.jpg)

But in win8 the "soda" them do that so will not crash, hope you fix these issue.
At most i like this theme.

**Comment by nilium** [comment]
I don't use Windows 8 (or any version of Windows for that matter) and I'm not going to install it to fix anything, so I'll leave this up to you or whoever else uses it. Submit a pull request if you fix it, just don't do anything that changes the theme visually.

Most likely this is a bug in Sublime, so it's really not my problem in the first place.
