### ISSUE TITLE
In Linux, dirty(unsaved) files not showing up with red underline on tab

### ISSUE THREAD

**Issue by nobleach** [nilium/st2-nil-theme#12]
Current file has a blue underline on the tab. Screenshots show a red underline (for what I'm guessing are unsaved files)

Opening a file, and making some edits does not cause the underline to be red when on another tab.

**Comment by nilium** [comment]
Wild guess: you didn't read the README, did you?

**Comment by nobleach** [comment]
highlight_modified_tabs

I'm sorry. I thought I read it thoroughly. I missed that key thing.
