### ISSUE TITLE
Unsaved changes indicator not showing in Sublime Text 3

### ISSUE THREAD

**Issue by thedamon** [nilium/st2-nil-theme#13]
Not sure if this is expected, or if it's an issue with ST3, but I thought I'd mention: the unsaved changes indicator doesn't show up in ver 3 (it does in the app in general). Other than that the theme seems to be functioning well in the new version

**Comment by nilium** [comment]
I'm assuming you've updated your Sublime Text 3 preferences to set `highlight_modified_tabs` to true (bearing in mind that your ST2 and ST3 preferences are separate)? 'Cause currently the indicator works fine for me, so I'm not sure under what conditions it would stop working.

**Comment by thedamon** [comment]
Whoops yes that does it! Thank you.
Because I was seeing a visual indicator on the default theme I guess I
assumed that I didn't need to change anything.

On Wed, Jan 30, 2013 at 11:08 AM, Noel Cower notifications@github.comwrote:

> I'm assuming you've updated your Sublime Text 3 preferences to set
> highlight_modified_tabs to true (bearing in mind that your ST2 and ST3
> preferences are separate)? 'Cause currently the indicator works fine for
> me, so I'm not sure under what conditions it would stop working.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nilium/st2-nil-theme/issues/13#issuecomment-12896815.

## 

Damon Muma
@thedamon
226-268-0544
http://www.whatisdamon.com
