### ISSUE TITLE
Add option to display folder icon for folders instead of arrows.

### ISSUE THREAD

**Issue by ghost** [nilium/st2-nil-theme#17]
Add option to display folder icon for folders instead of arrows, like Soda Theme has.
I got used to have folder icons on the left side.

**Comment by nilium** [comment]
Maybe, but first someone needs to contribute folder icons that fit the theme and have regular and HDPI resources. This isn't a priority for me, and the last person who tried to do this just copied resources from another theme.

So, to be up front about resource copying: I will not accept pull requests with folder icons someone ripped from another theme, regardless of whether permission was received to use them.

**Comment by ghost** [comment]
Sounds fair. Don't close this and I'll try and see if I can come up with something even tough I'm not good with graphics design, or maybe ask a friend who can do this, or maybe even someone who sees this can contribute.

**Comment by nilium** [comment]
Or wait a week until I'm done with graduation/moving/re-settling and then I'll see if I can try to do something.

**Comment by ghost** [comment]
Great. Good luck then.
