### ISSUE TITLE
Color for search bar highlighted

### ISSUE THREAD

**Issue by tnguyen14** [nilium/st2-nil-theme#18]
Hi,

I'm trying to modify your theme to suit my color scheme better, and when the Find/ Replace panel is brought up and there's text in the field, when the text is highlighted, there's a purple tint overlay on it (see attached)
![screen shot 2013-06-06 at 5 50 46 pm](https://f.cloud.github.com/assets/1652595/620972/2dc388c6-cef3-11e2-9d56-2d962e8aeb87.png)

Could you let me know where this color is defined?

Thanks!

**Comment by nilium** [comment]
It's in the [widgets file](https://github.com/nilium/st2-nil-theme/blob/master/Widget%20-%20Nil.stTheme).

**Comment by tnguyen14** [comment]
That's exactly what I needed! Thanks so much for the quick response! Your theme is awesome!
