### ISSUE TITLE
Can I change font of sidebar?

### ISSUE THREAD

**Issue by darth30joker** [nilium/st2-nil-theme#19]
Hi,

currently I am trying to change font face of sidebar, however I failed. The file I edited is Nil.sublime-theme, but I don't know which section should I modify. I tried several times, still failed.

So I am thinking, is it possible to change font for that? Including left sidebar and top sidebar of this theme?

**Comment by nilium** [comment]
Please don't create issues when it's not an issue. The font is probably theme-able, but I haven't looked into it. You'd have to ask Jon, who is the only person who knows what the thus-far undocumented theme properties all are.

**Comment by darth30joker** [comment]
Sorry

I will contact Jon for more details. Thanks!
