### ISSUE TITLE
Not marking the modified state

### ISSUE THREAD

**Issue by jiserra** [nilium/st2-nil-theme#2]
Hi, great theme! But I have a problem, when I modify a file, the theme it's not marking the modified state, nor in the tab or the sidebar. Do you know if any plugin can cause a conflict? I don't have problems with the 'dirty' state in other themes.

Thanks in advance!

**Comment by nilium** [comment]
See [issue #1](https://github.com/nilium/st2-nil-theme/issues/1), and if that doesn't resolve it, I haven't got the slightest idea.

**Comment by jiserra** [comment]
Yes, that resolve it, thanks! Sorry that I didn't see earlier there was an issue closed with that.
