### ISSUE TITLE
Close button in search bar (ST3)

### ISSUE THREAD

**Issue by PxlBuzzard** [nilium/st2-nil-theme#20]
Sublime Text 3 added a close button the right side of the search bar, as shown here:
![untitled](https://f.cloud.github.com/assets/512416/963343/473809f0-0501-11e3-8e4d-4266bbf63c4a.png)
Nil doesn't have this button, and I don't know if this was a deliberate decision or just something that was missed during the conversion from 2 to 3.

**Comment by nilium** [comment]
I've never done anything to support Sublime Text 3, and the current plan isn't to support it unless someone adds something in a way that doesn't break ST2 (which I use). Anyhow, if you're using the mouse to close the find panel, you're probably doing it wrong. Actually, if you're using the mouse at all, you're probably doing it wrong.

**Comment by nilium** [comment]
After making a new theme and seeing what the find bar's close button was, I decided it's a useless button and wastes space, so I'm closing this issue.
