### ISSUE TITLE
FR: Add ability to change sidebar padding / font size

### ISSUE THREAD

**Issue by Siyfion** [nilium/st2-nil-theme#21]
Firstly, I love the theme, well done!

I'd love to be able to change the "padding" and the font size in the sidebar, using a User Setting preferably, at the moment my sidebar has bigger and a more padded font than my code window! :+1:

**Comment by nilium** [comment]
I'd rather not go the Soda/that-other-theme-with-tons-of-options route. If you want to change the padding or font sizes, modify the theme file. I'll close this because it's impractical.
