### ISSUE TITLE
Repeated attribute in Nil theme for sidebar tree

### ISSUE THREAD

**Issue by nickcarenza** [nilium/st2-nil-theme#23]
Nil.sublime-theme
"dark_content": true
appears twice
line 425 and line 432

**Comment by nilium** [comment]
Not a bug.

**Comment by nickcarenza** [comment]
Sorry, I know it's not a bug. What is the right way to report small things like this? I didn't think it was worth forking and submitting a pull request. or is that the right way to do it?

**Comment by nilium** [comment]
Forking and submitting a pull request is the right way to do it. That way GitHub keeps track of contributors appropriately and I don't have to keep a list of contributors myself (though I probably should).
