### ISSUE TITLE
Visual glitches when used with st3

### ISSUE THREAD

**Issue by mengelbrecht** [nilium/st2-nil-theme#24]
I know your theme is primarily for st2 but because your theme looks so good I am using "Ayin" with st3 and discovered some small visual glitches.
- In the main window there is a 1px black border at the bottom of the editor view.
- In the find and replace view the border of the buttons and text field has an offset of 1px, but only partially

Is there a chance that these issues will get fixed or is st3 support out of scope?

**Comment by nilium** [comment]
Nil will remain an ST2 theme primarily, so minor glitches in ST3 aren't going to be fixed unless someone submits a fix themselves. As is, I'm using Freesia these days, so unless it affects me, I'm probably not going to do anything about it.

Might have something to do with layer content margins or padding if you want to take a crack at fixing it yourself.

**Comment by LOQUILLO** [comment]
Hi @mgee, I'll try fix this visual clitches.

**Comment by LOQUILLO** [comment]
Hi @mgee, you will should to be happiest.

**Comment by nilium** [comment]
Regarding #25 and #26 — Please do not submit pull requests that remove textures or contain commented-out data. Such changes will be rejected without question because removing a texture breaks the theme and leaving in unused data is sloppy.

This is not the Nexus theme (which is just a bad copy of an old version of the Nil theme, if I'm being frank). I do not plan to accept bad pull requests.

**Comment by LOQUILLO** [comment]
But this was tested for me, and dont break textures.

**Comment by nilium** [comment]
You removed the textures. That breaks textures.

**Comment by LOQUILLO** [comment]
![status-bar-bg](https://cloud.githubusercontent.com/assets/1308190/3277424/164cba32-f373-11e3-94ba-7c16829ab245.png)
Now I have the newest texture, so fix the bug https://github.com/nilium/st2-nil-theme/issues/24

**Comment by LOQUILLO** [comment]
Like I add for a PR?

**Comment by nilium** [comment]
The black border on the status bar is not a bug.

**Comment by mengelbrecht** [comment]
Thanks @nilium and @LOQUILLO for fixing this. It works great now.
