### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by vasylnakvasiuk** [nilium/st2-nil-theme#28]
Hi. Are these icons, what you expect?
![screen shot 2014-08-13 at 1 02 51 pm](https://cloud.githubusercontent.com/assets/139175/3903841/175e772a-22d1-11e4-9510-973e61b4a761.png)

Mac OS X 10.9.2
Sublime Text 3 (Build 3059)

**Comment by FichteFoll** [comment]
Yes, except for the rectangle.

**Comment by vasylnakvasiuk** [comment]
So, with my icons everything ok and we can close this issue?
