### ISSUE TITLE
Overlay bars have no Retina (@2x) equivalents.

### ISSUE THREAD

**Issue by davepeck** [nilium/st2-nil-theme#7]
First of all -- thanks so much for this theme. I dig the absolute minimalism.

I also dig the nearly-complete Retina support doesn't hurt either! Just a few details to go, it seems. 

For example, the graphics for overlay scrollbars don't appear to (yet) have `@2x` counterparts.

Cheers,
Dave

**Comment by nilium** [comment]
Overlay scrollbars aren't mine and, as I mentioned in the Sublime forum thread, I have no plans to replace 'em right now.  I simply don't use them, so I'm just waiting 'til the default theme is updated and then I'll be referencing its textures.  I frankly don't think I'm going to do a better job of them than the default theme has anyway.

**Comment by davepeck** [comment]
Understood. I'll close this and file against the upstream. Thanks again.
