### ISSUE TITLE
Font difference?

### ISSUE THREAD

**Issue by vdecree** [nilium/st2-nil-theme#8]
Got this installed correctly. Looks brilliant, only one thing though, im on a PC, and the font hasn't changed as per the screenshot, is the font in your screenshot only something mac users will get?

**Comment by vdecree** [comment]
My fault.. i found a post you made on a forum. I found the font, downloaded it and install via font squirrel, its now working fine.

**Comment by nilium** [comment]
Yep. I can't redistribute the font, and having the theme change users' font settings would be a terrible idea anyway. Us programmers are very specific about our fonts.

**Comment by haggen** [comment]
At least you could mention in the README what font you're using, right ? It's Envy Code R in case anyone enters here wondering (like I did).
